spring.application.name=demo

# ===== Configuración de correo (Gmail) =====
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# A qué correo quieres que lleguen los mensajes del formulario.
app.contacto.destino=${GMAIL_USERNAME}
